### PR TITLE
bump build number

### PR DESCRIPTION
**Pull request by garymm**
I'm hoping this will produce a package compatible with capnproto 1.0

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by garymm** [comment]
@conda-forge-admin, please rerender

**Comment by garymm** [comment]
@conda-forge-admin, please rerender

**Comment by garymm** [comment]
@conda-forge-admin, please rerender

**Comment by garymm** [comment]
@LehMaxence looks like this is good to go. Adds python 3.11 and capnproto 1.x support.

**Comment by LehMaxence** [comment]
> @LehMaxence looks like this is good to go. Adds python 3.11 and capnproto 1.x support.

Just curious why do you say it adds capnproto 1.x support?

Right now all the CI jobs use 0.10.2 because that's what is pinned so I'm not sure it actually works with v1. There's a [PR](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5377) open to pin v1.

**Comment by garymm** [comment]
> Just curious why do you say it adds capnproto 1.x support?


Because I'm a noob and I was wrong. I thought any version not specified in meta.yaml would use the latest version.
Anyways I'd like both py 3.11 and capnproto 1.x support, so I guess this PR gets us halfway there.
Any idea how to move that other PR forward?

**Comment by LehMaxence** [comment]
No worries, I was just wondering if you tried it out some other way.

You can probably ping `conda-forge/core` in the pinning PR to see if someone can look at it.

**Comment by LehMaxence** [comment]
Anyway I can merge this PR, and when the pinning is updated, the bot will open a new one here to update the package.

**Pull request merged**
