### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by szs8**
Updated md5 for 0.5.9

### CODE REVIEW

**Comment by szs8** [comment]
Seems to fail because something external to pycapnp.

**Comment by frol** [comment]
@jakirkham I see that there was an issue in conda-smithy and conda-build 2.0 (https://github.com/conda-forge/conda-smithy/issues/282). I also see that the pinning was applied. How should I proceed with this PR? Merging it now seems to me like a bad idea since the packages won't be published anyway.

**Comment by ocefpaf** [comment]
@frol and @szs8 you need to rerender the feedstock with latest conda-smithy.

```shell
conda install -c conda-forge conda-smithy
conda smithy rerender  # from the recipe root dir
```

**Comment by frol** [comment]
@ocefpaf This conda-build 2.0 compatibility issue seems to be common for every single feedstock. Should the conda-forge bot rerender all feedstocks then?

**Comment by ocefpaf** [comment]
Indeed. That would be better. Ping @pelson.

**Comment by jakirkham** [comment]
The bot is running as far as I know. It isn't running with the newest `conda-smithy` (unless it got updated), but it is new enough to have that fix. Though we could try amp up the rate that it generates the re-rendering PRs at. Would need to discuss that first though.

**Comment by frol** [comment]
Updated to 0.5.10 in #6.

**Pull request closed without merging**
